### ISSUE TITLE
hot reloading too fast

### ISSUE THREAD

**Issue by braytonstafford** [vercel/micro-dev#26]
I'm using webstorm 2017.2.1 and when I change focus from the editor to my browser i guess my .idea/workspace.xml gets changed causing node to stop because the port is in use (i'm using port 30100). Is there a way I can exclude certain directories from being watched by the hot reloader?

This is the console after i save index.js and change window focus over to my browser:
```
File changed: index.js - Restarting server...

File changed: .idea/workspace.xml - Restarting server...

File changed: .idea/workspace.xml - Restarting server...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::30100
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at doListen (net.js:1479:7)
    at _combinedTickCallback (internal/process/next_tick.js:105:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by braytonstafford** [comment]
Well I failed to search the closed issues before i open this and found a similar report.

This worked for me

```
micro-dev -p 30100 --ignore=**/.idea/**
```
